@php use App\Support\Money; @endphp
<main class="mx-auto max-w-7xl px-4 py-8 sm:px-6">
<div class="flex flex-wrap items-end justify-between gap-4"><div><h2 class="text-3xl font-black">Berichte</h2><p class="mt-1 text-slate-500">Tagesumsatz und Kassenschichten.</p></div><div class="flex items-end gap-2"><input wire:model.live="date" type="date" class="rounded-xl border border-slate-300 px-3 py-2"><button wire:click="downloadCsv" class="rounded-xl bg-slate-950 px-4 py-2 font-black text-white">CSV</button></div></div>
<div class="mt-6 grid gap-4 sm:grid-cols-3"><div class="rounded-3xl bg-white p-5 ring-1 ring-slate-200"><p class="text-sm font-bold text-slate-500">Umsatz</p><p class="text-3xl font-black">{{ Money::format($summary['revenue_cents'], $currency) }}</p></div><div class="rounded-3xl bg-white p-5 ring-1 ring-slate-200"><p class="text-sm font-bold text-slate-500">Verkäufe</p><p class="text-3xl font-black">{{ $summary['sales_count'] }}</p></div><div class="rounded-3xl bg-white p-5 ring-1 ring-slate-200"><p class="text-sm font-bold text-slate-500">Kostenlos</p><p class="text-3xl font-black">{{ $summary['free_sales_count'] }}</p></div></div>
<div class="mt-6 grid gap-6 lg:grid-cols-2">
<section class="rounded-3xl bg-white p-5 ring-1 ring-slate-200"><h3 class="font-black">Produkte</h3><div class="mt-3 divide-y divide-slate-100">@forelse($summary['products'] as $product)<div class="flex justify-between gap-3 py-2"><span>{{ $product['product_name'] }} · {{ $product['quantity'] }}×</span><strong>{{ Money::format($product['revenue_cents'], $currency) }}</strong></div>@empty<p class="py-4 text-slate-500">Keine Verkäufe.</p>@endforelse</div></section>
<section class="rounded-3xl bg-white p-5 ring-1 ring-slate-200"><h3 class="font-black">Kassenschichten</h3><div class="mt-3 divide-y divide-slate-100">@forelse($sessions as $session)<div class="py-2"><div class="flex justify-between"><span>{{ $session->register->name }}</span><strong>{{ Money::format((int)$session->closing_difference_cents, $currency) }}</strong></div><p class="text-sm text-slate-500">Soll {{ Money::format((int)$session->closing_expected_cash_cents, $currency) }} · gezählt {{ Money::format((int)$session->closing_counted_cash_cents, $currency) }}</p></div>@empty<p class="py-4 text-slate-500">Keine abgeschlossenen Schichten.</p>@endforelse</div></section>
</div>
</main>
